config/routes.rb
CocoonSimpleFormDemo::Application.routes.draw do

  resources :projects

  root :to => 'projects#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, inverse_of: :project
  has_many :people
  belongs_to :owner, :class_name => 'Person'

  has_many :project_tags, inverse_of: :project
  has_many :tags, :through => :project_tags, :class_name => 'Tag'

  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :people, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :owner, :reject_if => :all_blank
  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :project_tags, :allow_destroy => true

  validates_presence_of :name
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project

  accepts_nested_attributes_for :tag, :reject_if => :all_blank
end

app/models/sub_task.rb
class SubTask < ActiveRecord::Base
  belongs_to :task
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :project_tags, inverse_of: :tag
  has_many :projects, through: :project_tags
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :sub_tasks, inverse_of: :task
  accepts_nested_attributes_for :sub_tasks, :reject_if => :all_blank, :allow_destroy => true

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to(@project, :notice => 'successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end

  private

  def project_params
    params.require(:project).permit(
        :name, :description, :owner_id,
        tasks_attributes: [:id, :_destroy, :name, :description, sub_tasks_attributes: [:id, :_destroy, :name, :description] ],
        people_attributes: [:id, :name, :role, :description, :_destroy],
        owner_attributes: [:id, :name, :role, :description, :_destroy],
        project_tags_attributes: [:id, :_destroy, :tag_id, tag_attributes: [:id, :_destroy, :name]]
    )
  end
  def footer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title= "Mini Proj"
    = stylesheet_link_tag 'application'
    = javascript_include_tag "application"
    = csrf_meta_tag

body style='padding-top:40px;'
  #wrap
    .navbar.navbar-default.navbar-fixed-top role='navigation'
      .container
          ul.nav.navbar-nav
            li
              =link_to "Home", root_url
    .container
      == render :partial => 'shared/flashes'
      .row
        == yield

app/views/projects/_footer.html.erb
<h4>Designed By John &amp; Ajith </h4>

app/views/projects/_form.html.slim
= simple_form_for @project do |f|
  = f.input :name, :hint => 'The title of your taxanomy'


  .tab-content
    #tasks.tab-pane.active role='tabpanel'
      = f.simple_fields_for :tasks do |task|
        = render 'task_fields', :f => task
      .links
        = link_to_add_association 'add attribute  ', f, :tasks



  .actions
    = f.button :submit, :disable_with => 'Please wait ...'

app/views/projects/_owner_fields.html.slim
.nested-fields
  = f.input :name
  = f.input :role
  = f.input :description
  = link_to_remove_association "remove owner", f

app/views/projects/_person_fields.html.slim
.nested-fields
  = f.input :name
  = f.input :role
  = f.input :description
  = link_to_remove_association "remove person", f

app/views/projects/_project_tag_fields.html.slim
.nested-fields.project-tag-fields

  .form-inline
    .tag_from_list style="display: inline;"
      = f.association :tag, collection: Tag.order(:name), prompt: 'Choose an existing tag', label: false
    = link_to_add_association 'or create a new tag', f, :tag, class: 'add-tag'
    = link_to_remove_association f, class: 'remove-tag btn btn-default btn-xs' do
      .glyphicon.glyphicon-remove

app/views/projects/_sub_task_fields.html.slim
.nested-fields
  .form-inline
    b SubTask
    = f.input :name, placeholder: 'name the subtask', label: false
    = f.input :description, placeholder: 'add a description', label: false
    = link_to_remove_association f, class: 'btn btn-default btn-xs' do
      .glyphicon.glyphicon-remove

app/views/projects/_tag_fields.html.slim
.nested-fields.form-inline style='display:inline;'
  = f.input :name, :placeholder => 'how should it be tagged', :label => false

app/views/projects/_task_fields.html.slim
.nested-fields.well.well-compact
  .form-inline
    = f.input :name, :label => false, :placeholder => 'name the task', class: 'form-control'
    = f.input :description, :label => false, :placeholder => 'add a description', class: 'form-control'
    = f.input :done, :as => :boolean
    = link_to_remove_association f, data: {:confirm => 'do you really want to do this?'}, class: 'btn btn-default btn-xs' do
      .glyphicon.glyphicon-remove
  .sub_tasks
    = f.simple_fields_for :sub_tasks do |sub_task|
      = render 'sub_task_fields', :f => sub_task
    .links
      = link_to_add_association 'add sub-task', f, :sub_tasks

app/views/projects/edit.html.slim
h1 Editing details

== render 'form'

= link_to 'Show', @project
= '|'
= link_to 'Back', projects_path

app/views/projects/index.html.slim
h1 Listing Details

table.table
  thead
    tr
      th Name
      th Actions
  tbody
    - @projects.each do |project|
      tr
        td= project.name
        td
          = link_to 'Show', project, class: 'btn btn-default btn-xs'
          = link_to 'Edit', edit_project_path(project), class: 'btn btn-default btn-xs'
          = link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-xs btn-danger'


= link_to 'Create', new_project_path

app/views/projects/new.html.slim
input type="text" placeholder='search term' disabled=false
button = link_to 'search'
button = link_to 'Import'
h1 New project

== render 'form'

= link_to 'Back', projects_path

div id="footer"
  ==render 'footer'

app/views/projects/show.html.slim
h3 = link_to 'HOME', projects_path
h3 Tasks

p
  | List here

table.table
  -@project.tasks.each do |task|
    tr
      td= task.name
      td= task.description
      td= task.done

h3 Tags

table.table
  -@project.tags.each do |tag|
    tr
      td= tag.name


= link_to 'Edit', edit_project_path(@project)
= '|'
= link_to 'Back', projects_path

app/views/shared/_flashes.html.slim
.row
  - flash.each do |name, msg|
    - flash_type_translation = { 'notice' => 'warning', 'alert' => 'danger', 'success' => 'success'}
    - alert_class_name = flash_type_translation[name]
    .alert class="alert-#{alert_class_name || 'info'}"
      button.close type="button"  data-dismiss="alert"
        | &times;
      .message
        = msg